default:
  tags:
    - aws-linux

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}-node-modules
  paths:
    - node_modules/
    - .yarn/

test:
  image: node:18.17.1-alpine3.18
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn test
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - html-report
