default:
  tags:
    - aws-linux

stages:
  - test
test:
  image: node:16.15.1-alpine3.16
  stage: test
  script:
    - npm ci
    - npm test
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - html-report
