default:
  tags:
    - aws-linux
stages:
  - test
test:
  image: node:18.14.2-alpine3.17
  stage: test
  script:
    - yarn install --frozen-lockfile
    - yarn test
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - html-report
