const successSchema = {
  definitions: {},
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: '#success-get-skill-groups',
  title: 'Root',
  type: 'object',
  required: ['data', 'included', 'meta'],
  properties: {
    data: {
      $id: '#root/data',
      title: 'Data',
      type: 'array',
      default: [],
      items: {
        $id: '#root/data/items',
        title: 'Items',
        type: 'object',
        required: ['id', 'type', 'attributes', 'relationships'],
        properties: {
          id: {
            $id: '#root/data/items/id',
            title: 'Id',
            type: 'integer',
            examples: [69],
            default: 0,
          },
          type: {
            $id: '#root/data/items/type',
            title: 'Type',
            type: 'string',
            default: '',
            examples: ['skills'],
            pattern: '^.*$',
          },
          attributes: {
            $id: '#root/data/items/attributes',
            title: 'Attributes',
            type: 'object',
            required: [
              'name',
              'description',
              'factor',
              'external_id',
              'archived',
              'created_at',
              'updated_at',
            ],
            properties: {
              name: {
                $id: '#root/data/items/attributes/name',
                title: 'Name',
                type: 'string',
                default: '',
                examples: ['5 4 3 2 1 testei'],
                pattern: '^.*$',
              },
              description: {
                $id: '#root/data/items/attributes/description',
                title: 'Description',
                type: 'string',
                default: '',
                examples: [''],
                pattern: '^.*$',
              },
              factor: {
                $id: '#root/data/items/attributes/factor',
                title: 'Factor',
                type: 'integer',
                examples: [1],
                default: 0,
              },
              external_id: {
                $id: '#root/data/items/attributes/external_id',
                title: 'External_id',
                type: 'null',
                default: null,
              },
              archived: {
                $id: '#root/data/items/attributes/archived',
                title: 'Archived',
                type: 'boolean',
                examples: [false],
                default: true,
              },
              created_at: {
                $id: '#root/data/items/attributes/created_at',
                title: 'Created_at',
                type: 'string',
                default: '',
                examples: ['2022-06-30T17:17:50.508Z'],
                pattern: '^.*$',
              },
              updated_at: {
                $id: '#root/data/items/attributes/updated_at',
                title: 'Updated_at',
                type: 'string',
                default: '',
                examples: ['2022-07-19T14:23:38.699Z'],
                pattern: '^.*$',
              },
            },
          },
          relationships: {
            $id: '#root/data/items/relationships',
            title: 'Relationships',
            type: 'object',
            required: ['skill_group', 'positions'],
            properties: {
              skill_group: {
                $id: '#root/data/items/relationships/skill_group',
                title: 'Skill_group',
                type: 'object',
                required: ['links', 'data'],
                properties: {
                  links: {
                    $id: '#root/data/items/relationships/skill_group/links',
                    title: 'Links',
                    type: 'object',
                    required: ['related'],
                    properties: {
                      related: {
                        $id: '#root/data/items/relationships/skill_group/links/related',
                        title: 'Related',
                        type: 'string',
                        default: '',
                        examples: ['evaluation/api/skill_groups/73'],
                        pattern: '^.*$',
                      },
                    },
                  },
                  data: {
                    $id: '#root/data/items/relationships/skill_group/data',
                    title: 'Data',
                    type: 'object',
                    required: ['id', 'type'],
                    properties: {
                      id: {
                        $id: '#root/data/items/relationships/skill_group/data/id',
                        title: 'Id',
                        type: 'integer',
                        examples: [73],
                        default: 0,
                      },
                      type: {
                        $id: '#root/data/items/relationships/skill_group/data/type',
                        title: 'Type',
                        type: 'string',
                        default: '',
                        examples: ['skill_groups'],
                        pattern: '^.*$',
                      },
                    },
                  },
                },
              },
              positions: {
                $id: '#root/data/items/relationships/positions',
                title: 'Positions',
                type: 'object',
                required: ['data'],
                properties: {
                  data: {
                    $id: '#root/data/items/relationships/positions/data',
                    title: 'Data',
                    type: 'array',
                    default: [],
                  },
                },
              },
            },
          },
        },
      },
    },
    included: {
      $id: '#root/included',
      title: 'Included',
      type: 'array',
      default: [],
      items: {
        $id: '#root/included/items',
        title: 'Items',
        type: 'object',
        required: ['id', 'type', 'attributes'],
        properties: {
          id: {
            $id: '#root/included/items/id',
            title: 'Id',
            type: 'integer',
            examples: [68],
            default: 0,
          },
          type: {
            $id: '#root/included/items/type',
            title: 'Type',
            type: 'string',
            default: '',
            examples: ['skill_groups'],
            pattern: '^.*$',
          },
          attributes: {
            $id: '#root/included/items/attributes',
            title: 'Attributes',
            type: 'object',
            required: ['name'],
            properties: {
              name: {
                $id: '#root/included/items/attributes/name',
                title: 'Name',
                type: 'string',
                default: '',
                examples: ['teste 2'],
                pattern: '^.*$',
              },
              external_id: {
                $id: '#root/included/items/attributes/external_id',
                title: 'External_id',
                type: 'null',
                default: null,
              },
              archived: {
                $id: '#root/included/items/attributes/archived',
                title: 'Archived',
                type: 'boolean',
                examples: [false],
                default: true,
              },
              created_at: {
                $id: '#root/included/items/attributes/created_at',
                title: 'Created_at',
                type: 'string',
                default: '',
                examples: ['2022-06-28T14:25:38.118Z'],
                pattern: '^.*$',
              },
              updated_at: {
                $id: '#root/included/items/attributes/updated_at',
                title: 'Updated_at',
                type: 'string',
                default: '',
                examples: ['2022-06-28T14:25:38.118Z'],
                pattern: '^.*$',
              },
            },
          },
        },
      },
    },
    meta: {
      $id: '#root/meta',
      title: 'Meta',
      type: 'object',
      required: ['pagination'],
      properties: {
        pagination: {
          $id: '#root/meta/pagination',
          title: 'Pagination',
          type: 'object',
          required: [
            'current',
            'previous',
            'next',
            'per_page',
            'pages',
            'total_count',
          ],
          properties: {
            current: {
              $id: '#root/meta/pagination/current',
              title: 'Current',
              type: 'integer',
              examples: [1],
              default: 0,
            },
            previous: {
              $id: '#root/meta/pagination/previous',
              title: 'Previous',
              type: 'null',
              default: null,
            },
            next: {
              $id: '#root/meta/pagination/next',
              title: 'Next',
              type: 'null',
              default: null,
            },
            per_page: {
              $id: '#root/meta/pagination/per_page',
              title: 'Per_page',
              type: 'integer',
              examples: [20],
              default: 0,
            },
            pages: {
              $id: '#root/meta/pagination/pages',
              title: 'Pages',
              type: 'integer',
              examples: [1],
              default: 0,
            },
            total_count: {
              $id: '#root/meta/pagination/total_count',
              title: 'Total_count',
              type: 'integer',
              examples: [12],
              default: 0,
            },
          },
        },
      },
    },
  },
};

export default successSchema;
